const money = value => `$${value.toLocaleString('en-US')}`;
const state = { build: {}, filter: 'All', search: '' };
const $ = selector => document.querySelector(selector);
function productCard(product) { return `<article class="product-card"><button class="product-image" data-product="${product.id}" aria-label="View ${product.name}"><img src="${product.image}" alt="${product.name}"><span class="view-product">View details ↗</span></button><div class="product-meta"><span class="product-category">${product.category}</span><h3>${product.name}</h3><p>${product.specs}</p><strong>${money(product.price)}</strong></div></article>`; }
function renderHome() { $('#category-grid').innerHTML = categories.map(category => `<a class="category-card" href="#components" data-category="${category.type}"><span class="category-icon">${category.icon}</span><span><strong>${category.name}</strong><small>${category.count} <b>↗</b></small></span></a>`).join(''); $('#featured-grid').innerHTML = products.filter(product => product.featured).map(productCard).join(''); }
function renderFilters() { const types = ['All', ...new Set(products.map(product => product.category))]; $('#filter-buttons').innerHTML = types.map(type => `<button class="filter-button ${state.filter === type ? 'active' : ''}" data-filter="${type}">${type}</button>`).join(''); }
function renderCatalog() { const visible = products.filter(product => (state.filter === 'All' || product.category === state.filter) && `${product.name} ${product.specs}`.toLowerCase().includes(state.search.toLowerCase())); $('#catalog-grid').innerHTML = visible.length ? visible.map(productCard).join('') : '<div class="empty-state">No components match that search.</div>'; renderFilters(); }
function renderDetails(id) { const product = products.find(item => item.id === id) || products[0]; $('#details-content').innerHTML = `<a class="back-link" href="#components">← Back to components</a><div class="detail-layout"><div class="detail-image"><img src="${product.image}" alt="${product.name}"></div><div class="detail-copy"><p class="eyebrow">${product.category} / ASHARS SELECT</p><h1>${product.name}</h1><p class="detail-specs">${product.specs}</p><strong class="detail-price">${money(product.price)}</strong><p>A dependable choice for a focused, high-performance build. We chose this part for its balanced thermals, sensible feature set, and long-term value.</p><button class="button button-primary" data-add-build="${product.id}">Add to PC builder <span>→</span></button><div class="detail-facts"><span><b>Warranty</b> 3 years</span><span><b>Availability</b> In stock</span><span><b>Shipping</b> 24 hours</span></div></div></div>`; }
function renderBuilder() { const order = ['CPU', 'Motherboard', 'GPU', 'RAM', 'Storage', 'PSU', 'Case', 'Cooler']; $('#builder-options').innerHTML = order.map(category => `<div class="builder-row"><div><span class="builder-number">${String(order.indexOf(category) + 1).padStart(2, '0')}</span><strong>${category}</strong></div><select data-build-category="${category}"><option value="">Choose ${category.toLowerCase()}...</option>${products.filter(product => product.category === category).map(product => `<option value="${product.id}" ${state.build[category] === product.id ? 'selected' : ''}>${product.short} — ${money(product.price)}</option>`).join('')}</select></div>`).join(''); const selected = order.map(category => products.find(product => product.id === state.build[category])).filter(Boolean); $('#selected-parts').innerHTML = selected.length ? selected.map(product => `<div class="selected-part"><span>${product.category}</span><strong>${product.short}</strong><b>${money(product.price)}</b></div>`).join('') : '<p class="no-parts">Your build is waiting for its first part.</p>'; $('#total-price').textContent = money(selected.reduce((total, product) => total + product.price, 0)); const cpu = selected.find(product => product.category === 'CPU'); const board = selected.find(product => product.category === 'Motherboard'); const hasPair = cpu && board; const compatible = !hasPair || cpu.socket === board.socket; $('#compatibility-badge').textContent = !hasPair ? 'Waiting' : compatible ? 'Compatible' : 'Needs attention'; $('#compatibility-badge').className = `compat-badge ${!hasPair ? '' : compatible ? 'good' : 'warning'}`; $('#compatibility-message').textContent = !hasPair ? 'Select a CPU and motherboard to begin compatibility checks.' : compatible ? 'Your CPU and motherboard share the AM5 socket.' : 'The selected CPU and motherboard use different sockets.'; }
function navigate() { const hash = location.hash.slice(1) || 'home'; const page = hash.startsWith('details/') ? 'details' : hash; document.querySelectorAll('.page-view').forEach(view => view.classList.toggle('active', view.dataset.page === page)); document.querySelectorAll('.main-nav a').forEach(link => link.classList.toggle('active', link.getAttribute('href') === `#${page}`)); if (page === 'details') renderDetails(hash.split('/')[1]); window.scrollTo(0, 0); }
renderHome(); renderCatalog(); renderBuilder(); navigate();
document.addEventListener('click', event => { const productButton = event.target.closest('[data-product]'); if (productButton) location.hash = `details/${productButton.dataset.product}`; const filter = event.target.closest('[data-filter]'); if (filter) { state.filter = filter.dataset.filter; renderCatalog(); } const category = event.target.closest('[data-category]'); if (category) { state.filter = category.dataset.category; renderCatalog(); } const add = event.target.closest('[data-add-build]'); if (add) { const product = products.find(item => item.id === add.dataset.addBuild); state.build[product.category] = product.id; location.hash = 'builder'; renderBuilder(); } if (event.target.closest('#reset-build')) { state.build = {}; renderBuilder(); } if (event.target.closest('.menu-toggle')) $('.main-nav').classList.toggle('open'); });
document.addEventListener('input', event => { if (event.target.id === 'product-search') { state.search = event.target.value; renderCatalog(); } });
document.addEventListener('change', event => { if (event.target.matches('[data-build-category]')) { state.build[event.target.dataset.buildCategory] = event.target.value; renderBuilder(); } });
$('#contact-form').addEventListener('submit', event => { event.preventDefault(); $('#form-message').textContent = 'Thanks, your message is ready for us. We will be in touch soon.'; event.target.reset(); });
window.addEventListener('hashchange', navigate);